# Docker file for setting up kafka

version: '4'
services:
  
  # This is kafka service
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
      - "2181:2181"
    volumes:
      - "./sample/local-kafka-data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

  # New API service
  internal_new_micro_service:
    # This is the server that handles all external calls
    image: node:18.16.1-alpine3.18
    depends_on:
      - kafka
    environment:
      SERVER_PORT: ${NEW_API_SERVER_PORT}
    ports:
      - ${NEW_API_SERVER_PORT}:${NEW_API_SERVER_PORT}
    volumes:
      - ./sample/new_api:/app
    command: >
      sh -c "cd /app && env && npm install  && sleep 5 && node setup/setup.js && sleep 5 &&
             node src/main.js "


  # Old API service
  internal_old_micro_service:
    # This is the server that handles all external calls
    image: python:3.10.12-alpine3.18
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 0
      SERVER_PORT: ${OLD_API_SERVER_PORT}
    ports:
      - ${OLD_API_SERVER_PORT}:${OLD_API_SERVER_PORT}
    volumes:
      - ./sample/old_api:/app
    command: >
      sh -c "cd /app && env && echo INSTALLING REQUIREMENTS && cat requirements.txt &&  pip install -r requirements.txt && sleep 10 && python -m flask --app src/main run --host=0.0.0.0 --port=${OLD_API_SERVER_PORT} "

  # The router
  router:
    # This is the server that handles all external requests
    image: node:18.16.1-alpine3.18
    depends_on:
      - kafka
    environment:
      SERVER_PORT: ${ROUTER_SERVER_PORT}
      OLD_API_SERVER_URL: http://internal_old_micro_service:${OLD_API_SERVER_PORT}
      NEW_API_SERVER_URL: http://internal_new_micro_service:${NEW_API_SERVER_PORT}
    ports:
      - ${ROUTER_SERVER_PORT}:${ROUTER_SERVER_PORT}
      - 9229:9229
    volumes:
      - ../router:/app
    command: >
      sh -c "cd /app && env && npm install  && sleep 12 &&
             node --inspect=0.0.0.0:9229 src/main.js "


  
    
